# Generated by Django 5.1.15 on 2026-07-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora do Acesso')),
                ('hash_visitante', models.CharField(db_index=True, max_length=64, verbose_name='Hash do Visitante')),
                ('dispositivo', models.CharField(default='Desktop', max_length=30, verbose_name='Dispositivo')),
                ('caminho', models.CharField(default='/', max_length=100, verbose_name='Página/Rota')),
            ],
            options={
                'verbose_name': 'Registro de Acesso',
                'verbose_name_plural': 'Registros de Acessos',
                'ordering': ['-data'],
            },
        ),
    ]
