# Generated by Django 5.1.1 on 2024-09-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField(default=str)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pratos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pratos.categoria')),
            ],
            options={
                'verbose_name': 'Prato',
            },
        ),
    ]
