# Generated by Django 5.1.1 on 2024-09-07 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterField(
            model_name='prato',
            name='descricao',
            field=models.TextField(default=str, max_length=200),
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pratos.categoria')),
            ],
            options={
                'verbose_name': 'SubCategoria',
            },
        ),
    ]
