# Generated by Django 5.1.1 on 2026-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0002_alter_categoria_options_alter_prato_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço promocional'),
        ),
        migrations.AddField(
            model_name='prato',
            name='promocao',
            field=models.BooleanField(default=False, verbose_name='Em promoção?'),
        ),
    ]
