# Generated by Django 5.1.15 on 2026-07-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratos', '0003_prato_preco_promocional_prato_promocao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategoria',
        ),
    ]
